language: bash
install:
  - ./build/install.sh
script:
  - ./build/build.sh
  - source jvm.sh
  - jvm local 7
  - jvm reload
  - jvm version
  - java -version
notifications:
  email: false
sudo: required
os:
  - linux
  - osx
