language: bash
install:
  - ./build/install.sh
script:
  - ./build/build.sh
  - test "$TRAVIS_OS_NAME" = "osx" && brew cask install java
  - ./tests/test.sh
notifications:
  email: false
sudo: required
os:
  - linux
  - osx
